---
- name: Install Nginx
  hosts: all
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: Nginx
        state: present
    - name: Start Nginx
      service:
        name: Nginx
        state: started
